### ISSUE TITLE
test_flake8 doesn't work with flake8 3.8

### ISSUE THREAD

**Issue by kyrofa** [dirk-thomas/vcstool#139]
flake8 3.8 changes the Application API such that test_flake8 no longer works:

```
=================================================================== FAILURES ===================================================================
_________________________________________________________________ test_flake8 __________________________________________________________________

    def test_flake8():
        configure_logging(1)
        argv = [
            '--extend-ignore=' + ','.join([
                'A003', 'D100', 'D101', 'D102', 'D103', 'D104', 'D105', 'D107']),
            '--exclude', 'vcstool/compat/shutil.py',
            '--import-order-style=google']
>       style_guide = get_style_guide(argv)

test/test_flake8.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

argv = ['--extend-ignore=A003,D100,D101,D102,D103,D104,D105,D107', '--exclude', 'vcstool/compat/shutil.py', '--import-order-style=google']

    def get_style_guide(argv=None):
        # this is a fork of flake8.api.legacy.get_style_guide
        # to allow passing command line argument
        application = Application()
>       application.parse_preliminary_options_and_args([])
E       AttributeError: 'Application' object has no attribute 'parse_preliminary_options_and_args'

test/test_flake8.py:40: AttributeError
=========================================================== short test summary info ============================================================
FAILED test/test_flake8.py::test_flake8 - AttributeError: 'Application' object has no attribute 'parse_preliminary_options_and_args'
======================================================== 1 failed, 16 passed in 14.55s =========================================================
```

Consider pinning to 3.7.9 or updating the test.

**Comment by dirk-thomas** [comment]
Thanks for the report.
